server:
  port: 9000

spring:
  application:
    name: edge-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edge-service
            client-secret: polar-keycloak-secret
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/PolarBookshop

  cloud:
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
        - name: CustomGatewayFilter
          args:
            myParam: "SomeValue"
      routes:
        - id: book-route
          uri: ${BOOK_SERVICE_URL:http://localhost:9001}
          predicates:
            - Path=/books/**

